### PR TITLE
Use getpass to grab ambari password

### PR DESCRIPTION
**Pull request by thesquelched**
Kind of sucks if you have to put your password in plaintext on the command line.

### CODE REVIEW

**Comment by cryptickp** [comment]
:+1:  For anyone who is not familiar with [getpass](https://pymotw.com/2/getpass/)

**Comment by pchanne** [comment]
Shouldn't we make all the credentials create consistent? Why this particular one needs ``getpass`` ?

**Comment by amock** [comment]
+1

**Comment by thesquelched** [comment]
@pchanne because it's the only one that uses a password.  The other credentials are like API keys

**Comment by pchanne** [comment]
@thesquelched, I thought API keys should be equally secure as well. I am not opposed to using the idea of using ``getpass`` though. Don't want to block this. +1

**Pull request merged**
