### PR TITLE
Clarify current status of credential updates

### PR DESCRIPTION
**Pull request by thesquelched**
Minor documentation update on credentials.

### CODE REVIEW

**Comment by jimbobhickville** [comment]
@thesquelched py26 error in the tests. functools something or other.  Not sure how this PR triggered that error since it didn't touch any actual code.  Also, why does the py26 test say it's running Python 3.4?

**Comment by thesquelched** [comment]
It says "python3.4" because that's the underlying python that's calling `tox`

**Comment by thesquelched** [comment]
Wow, brilliant job `oslo_config`, you added a python 2.7 specific function to your library.

**Comment by thesquelched** [comment]
Really, `oslo.config`? https://github.com/openstack/oslo.config/commit/9470f19eacb99425055946bd4a6079b71406ff1b

They dropped support for python 2.6 intentionally.  Now I've got to root it out of the code somehow, or stick to an older version?

**Comment by thesquelched** [comment]
What a stupid, lazy thing to drop python 2.6 support for.  `total_ordering` can be *easily* accomplished with a handful of magic methods.

**Comment by jimbobhickville** [comment]
+1 - although I think the real solution is to stop using keystoneclient and just get the token manually with requests.

**Comment by rnirmal** [comment]
+1 yeah would be good to get rid of keystoneclient. We aren't doing a whole lot there and should be easy to switch to requests.

**Pull request merged**
