### PR TITLE
Add service management methods

### PR DESCRIPTION
**Pull request by thesquelched**
You can now start/stop/restart services on a cluster, so long as they're running Ambari (which is pretty much everything).

### CODE REVIEW

**Comment by jimbobhickville** [comment]
+1

**Comment by jimbobhickville** [comment]
Looks like a keystoneclient update broke the build.  Go figure.

**Comment by thesquelched** [comment]
Tests are good now @jimbobhickville

**Comment by pchanne** [comment]
+1

**Pull request merged**
